stages:
  split:
    cmd: python src/split.py data/creditcard.csv data/split params.yaml
    deps:
      - src/split.py
      - data/creditcard.csv
    params:
      - split
    outs:
      - data/split

  prepare:
    cmd: python src/prepare.py data/split data/prepared params.yaml
    deps:
      - src/prepare.py
      - data/split
    params:
      - prepare
    outs:
      - data/prepared

  train:
    cmd: python src/train.py data/prepared/train.csv model.json params.yaml
    deps:
      - src/train.py
      - data/prepared/train.csv
    params:
      - train
    outs:
      - model.json
      - metrics/validation.json
      - plots/cm
      - plots/prc

metrics:
  - metrics/validation.json

plots:
  - Confusion-Matrix:
      template: confusion
      x: actual
      y:
        plots/cm/train.csv: predicted
        plots/cm/validation.csv: predicted
  - Confusion-Matrix-normalized:
      template: confusion_normalized
      x: actual
      y:
        plots/cm/train.csv: predicted
        plots/cm/validation.csv: predicted

  - Precision-Recall:
      template: simple
      x: recall
      y:
        # eval/plots/sklearn/prc/train.json: precision
        plots/prc/validation.json: precision
